imapclient/imapclient.py
imapclient/test/test_imapclient.py

In the last day we’ve seen this ValueError 249,915 times. It looks like the response can be more than two parts if A) the mailbox name contains spaces or B) the server decides to send us other data (or IMAPClient rolls it into the response buffer, not clear yet.) Either way, we should be able to handle these scenarios without crashing.
Relevant internal logs: https://nylas.loggly.com/search#terms=%22folder_status%20ValueError%22&from=2016-09-02T01%3A57%3A05.585Z&until=2016-09-03T01%3A57%3A05.585Z&source_group=

Tests for bad data in folder_status, more robust handling

---

imapclient/datetime_util.py

Thanks to frispete (https://github.com/frispete) for the initial patch

datetime_to_INTERNALDATE: use plain english month abbreviations

---

README.rst
doc/src/index.rst
setup.py
tox.ini

We successfully run imapclient with Python 3.6 on production for a few months already.

Officially support Python 3.6

---

doc/src/index.rst
doc/src/releases.rst
imapclient/imapclient.py
imapclient/test/test_imapclient.py
imapclient/test/testable_imapclient.py

Instead of a custom way of managing log lines, this commit
leverages the standard logging module. As IMAPClient is a library,
the only thing to do is to create a logger and log away.
The final user of IMAPClient is now in charge of formatting,
writing to files or discarding log lines.

Use the standard logging module

---

imapclient/config.py

To reply to the deleted comment `# TODO: can't six do this for us?` in the codebase, yes we can.

Use six instead of try/except for ConfigParser import

---

doc/src/releases.rst
imapclient/imapclient.py
imapclient/livetest.py
imapclient/test/test_imapclient.py

As said in the commitmsg, this is still a work in progress. Things missing:
Does `unselect_folder()` is useful as a public method if we favor the `select_folder(None)`? I would prefer to keep a single _public_ way to use it. 
My two cents: I like the `(None)` one (it reminds me [Django convetion for select_related/prefetch_related](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#select-related)) but `unselect_folder` as a separate method can be valid since it is a different IMAP command...
Issue reference: #200

#200 - Add UNSELECT command

---

imapclient/imapclient.py
tests/test_imapclient.py

Even if the final user did not enable DEBUG logging for its
application, some logs records can end up in tools like Sentry
via breadcrumbs.
This commit makes sure that passwords are never sent to the
logging system by verifying and redacting the log message before
passing it to the logger.
In the future, once we get rid of imaplib, the code replacing it
could avoid logging raw data containing sensitive information in
the first place.

Prevent IMAP passwords from going to the logging system

---

doc/src/releases.rst
imapclient/config.py
imapclient/imapclient.py
tests/test_init.py

Support for SSL/TLS in both Python and IMAP servers is good enough
to make it a sensible default.
Users can still establish connections over plain text by passing
`ssl=False` when instantiating an `IMAPClient` object.
Fixes #273

Establish secure connections by default

---

doc/src/advanced.rst
doc/src/index.rst
doc/src/releases.rst
imapclient/imapclient.py
tests/test_imapclient.py

To prevent users of the library from inadvertently leaking
sockets.
Fixes #276

Introduce a context manager that closes opened connections

---

doc/src/api.rst
imapclient/exceptions.py
imapclient/imapclient.py
livetest.py
tests/test_auth.py
tests/test_enable.py
tests/test_imapclient.py
tests/test_search.py
tests/test_sort.py
tests/test_starttls.py
tests/test_thread.py
tests/test_util_functions.py

This is a quick draft but I want a first approval before continuing this way, since it will require a lot of code to adapt.
I have defined a new module `imapclient.exceptions` that defines all types of exceptions that IMAPClient might raise. This is very similar [to what requests/django/pytz are doing](https://github.com/requests/requests/blob/master/requests/exceptions.py). The base class is actually just `imap.IMAP4.error` so we can still rely on `except imap.IMAP4.error` if we don't care at all about the source of the exception (+ backward compatibility with 1.x code) 
The most-time consuming is now to define what exceptions we need (I wrote down a couple of them) and raise them in the appropriate methods. 
Most of the exceptions raised in IMAPClient are actually exceptions that bubble …

#141 - Use precise exceptions for each type of error

---

imapclient/imapclient.py
imapclient/livetest.py
imapclient/test/test_imapclient.py

Patch to allow EXPUNGE by ID, and avoid the problem where folder-wide expunge deletes all messages.
Implements one item on the list for https://github.com/mjs/imapclient/issues/36
The idea is to overload arguments to expunge(): if messages are specified, do a `'UID EXPUNGE <messages>'`, else it is a folder-wide expunge(). The former won't work if `use_uid=False`. (I don't have insight how many IMAPClient users turn off uid's, and whether this would be better as a different method).
The return type is None when expunge-ing by id. imaplib.py returns `('OK', [None])` from a `UID EXPUNGE`.

allow EXPUNGE by ID

---

doc/src/api.rst
doc/src/releases.rst
imapclient/config.py
imapclient/imap4.py
imapclient/imapclient.py
imapclient/tls.py
livetest.py
tests/test_imapclient.py
tests/test_init.py

Still a WIP, seems to work on my mailbox, further tests would be appreciated. Things to do:

#285 - Separate connect timeout from read/write timeout

---

README.rst
doc/src/advanced.rst
doc/src/concepts.rst
doc/src/contributing.rst
doc/src/index.rst
doc/src/installation.rst
doc/src/quickstart.rst

* Document how to use IDLE
* Write a note about thread safety
* Split installation into its own page
* Simplify a bit the README
* Mention that `backports.ssl` is just a compatibility layer

Improve documentation

---

doc/src/releases.rst
imapclient/imap_utf7.py
tests/test_imap_utf7.py

Instead of trying to fix the existing code for the encoder (the part that was buggy in issue #187), I took the RFC and follow each step to reproduce the algorithm. The initial code was almost correct (I guess the problem came from the missing `rstrip` I add in `base64_utf7_encode`) but anyway, my version has better variable names and comments... 😅
I've also renamed variables in the decode function to make it consistent + easier to read later. Also added comments to explain what it does.
Finally, I added the use case that was failing in the issue to validate it. If you see any other cases failing with the 1.0.2 implementation and that would be interesting for the non-regression test, please let me know.

Refactor imap_utf7 module to make it easier to understand and fix #187

---

imapclient/config.py
livetest.py

Both commits are really cleanup routine, they should be self-explanatory

Clean up and fix flickering livetest due to config manipulation

---

imapclient/imapclient.py
tests/test_search.py

I've run into a problem when using the search criterion `HEADER`. As [RFC 3501](https://tools.ietf.org/html/rfc3501#section-6.4.4) tells us the syntax is `HEADER <field-name> <string>`. It also says: " If the string to search is zero-length, this matches all messages that have a header line with the specified field-name regardless of the contents."
When you issue `server.search(['HEADER', 'List-Id', ''])` the zero-length argument is ignored resulting in a syntax error.
This pull request fixes this problem. I do not know whether this is the right place to fix this problem but if so I would be glad if the PR could be merged.

quote empty strings as otherwise they would be ignored by the server

---

imapclient/util.py
tests/test_response_parser.py

Ignore invalid encoding in Address string representation

---

doc/src/api.rst
doc/src/concepts.rst
doc/src/conf.py
doc/src/releases.rst
imapclient/config.py
imapclient/imapclient.py
imapclient/tls.py
setup.py

As said in #217, `backports.ssl` is no longer needed with Python 2.7+ and 3.4+ and it brings more problems than it resolves. Since it is no longer needed per our support plan, this PR removes any usage of `backports.ssl` + the dependency in setup.py.

Remove backports.ssl dependency

---

setup.py

The newest version of cryptography dropped support for Python 3.3.
Fixes #305

Use cryptography < 2.0 on Python 3.3

---

doc/src/concepts.rst
imapclient/tls.py
imapclient/version.py

The modern implementation of ssl using SSLContext appeared in
Python 2.7.9. Previous versions can use encrypted connections but
cannot precisely configure it.
Fixes #301

Allow old version of Python 2.7 to use TLS

---

doc/src/releases.rst
imapclient/imapclient.py
livetest.py

Allows to move messages in a single call without going through
copy + flag deleted + expunge.
Fixes #142

Add support for UID MOVE (RFC 6851)

---

doc/src/releases.rst
imapclient/imapclient.py
livetest.py
tests/test_store.py

Encode/decode GMail labels using UTF-7 so that international
characters are handled correctly.
This has the effect of slightly changing IMAPClient API as labels
are now str in Python 3 and unicode in Python 2.7.
Fixes #181

Handle GMail labels with international characters

---

imapclient/config.py
imapclient/tls.py

The ssl contexts are created to authenticate servers so we should
use `ssl.Purpose.SERVER_AUTH` which is the default.
Fixes #317

Use correct ssl purpose

---

doc/src/releases.rst
imapclient/exceptions.py
imapclient/imapclient.py
imapclient/response_lexer.py
imapclient/response_parser.py
imapclient/util.py
tests/test_imapclient.py
tests/test_response_parser.py
tests/test_util_functions.py

To allow users to recover from bad server responses without
catching broad AssertionError, a new exception is introduced.
Fixes #288

Avoid using assert when parsing server response

---

AUTHORS.rst
README.rst
doc/src/advanced.rst
doc/src/api.rst
doc/src/concepts.rst
doc/src/conf.py
doc/src/contributing.rst
doc/src/index.rst
doc/src/quickstart.rst
examples/example.py
examples/idle_example.py
examples/tls_cacert.py
examples/tls_no_checks.py
setup.py

* Include a decent example in README 
* Correct many things that were no longer true due to recent changes
* Fixed typos and improved wording throughout
Closes #275.

Documentation improvements

---

imapclient/imapclient.py
tests/test_imapclient.py

Configuring special folders is often a pain that requires the
owner of an account to give the location of folders himself.
With the help of IMAP extensions and a few assumptions we can try
to guess where these folders are. In practice this is enough for
the vast majority of accounts.
Related to #296

Locate special folders like Sent or Trash

---

imapclient/imapclient.py
tests/test_enable.py
tests/test_imapclient.py
tests/test_search.py
tests/test_starttls.py

All methods that rely on IMAP extensions are decorated to raise a
CapabilityError if the server does not support it.
Fixes #333

Always check that the server supports a capability

---

imapclient/response_parser.py
tests/test_response_parser.py

NIL is already converted to None during parsing.
The .upper() call on None will cause AttributeError. Catch this case
early and return None early.

Fix error when INTERNALDATE is NIL

---

imapclient/interact.py

* Changed default parameters (and description) in command line parser

Use TLS by default in interactive session

---

tests/test_imapclient.py

Addresses changes made by CPython commit ce9e62544571e7ad.

Fix log test in Python 3.7

---

imapclient/imapclient.py

Not sure why are we catching ValueError here. I don't think it will ever raise ValueError just by assigning list/tuple's index -1 item to a variable. The exception I got from `response[-1]` is IndexError when the response is an empty list. But if we catch IndexError, `str(response)` is certainly empty list/tuple. Do we still want that exception message?

Catch the right exception in folder_status

---

imapclient/imapclient.py

Python 2.7.12:
```
In [10]: def _maybe_int_to_bytes(val):
...:     if isinstance(val, integer_types):
...:         return str(val).encode('us-ascii')
...:     return to_bytes(val)
...: 
In [11]: %timeit _maybe_int_to_bytes(1000)
The slowest run took 15.50 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 585 ns per loop
In [22]: def _maybe_int_to_bytes(val):
...:     if isinstance(val, integer_types):
...:         return str(val).encode('us-ascii') if PY3 else str(val)
...:     return to_bytes(val)
...: 
In [25]: %timeit _maybe_int_to_bytes(1000)
The slowest run took 15.67 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 243 ns per loop
``` …

2x faster _maybe_int_to_bytes for Python 2

---

imapclient/imapclient.py
imapclient/util.py

Testing / benchmarking script:
```
import time
import timeit
import itertools
import six
import perfplot
time.perf_counter = timeit.default_timer
def chunk_len(lst, n):
for i in six.moves.range(0, len(lst), n):
yield lst[i:i + n]
def chunk_iter(iterable, size):
it = iter(iterable)
while True:
chnk = tuple(itertools.islice(it, None, size))
if not chnk:
return
yield chnk
def f1(lst):
while lst:
a, b, c = lst[:3]
lst = lst[3:]
def f2(lst):
for a, b, c in chunk_len(lst, 3):
pass
def f3(lst):
for a, b, c in chunk_iter(lst, 3):
pass
perfplot.show(
setup=lambda n: range(n),  # or simply setup=numpy.random.rand
kernels=[f1, f2, f3],
labels=['f1', 'f2', 'f3'],
n_range=[3 * i for i in range(0, 10000, 500)],
equality_check=None,
)
```
Although the iterator version is more elegant, I went for the …

Fix _proc_folder_list quadratic runtime

---

imapclient/imap_utf7.py

~40% faster for input with a mix of unicode and ascii chars. The improvement is more significant for pure ascii chars.
This is achieved by removing the .encode() in the most common path (ascii char) and comparing ordinal values instead of unicode objects.
Actually we can get 10% more by eliminating dot notation, 10-20% more by inlining `consume_b64_buffer` function, some more by caching `ord` global function, but then the code will get quite ugly and I'm not sure if that's welcomed.

Faster utf7 encode

---

imapclient/imapclient.py

Cache the regex object explicitly instead of relying on Python `re`'s internal cache. Using `.match` from object instead of `re` skips the checking of internal cache so this change is faster either the internal cache is full or not. Since this is more like a micro-optimization, the benchmark may not be stable but the avg results are definitely better (by at least 10%). After all, it is always more reasonable to explicitly cache a regex object.
Before: 1.49s
After: 1.27s
Benchmark code:
```
import mock
import time
from timeit import timeit
import re
class PatchedDict(dict):
def __get__(self, *args, **kwargs):
return None
re._cache = PatchedDict()
from imapclient import IMAPClient
N = 100000
resp = {'OK': ['[PERMANENTFLAGS ()] Flags permitted.', '[UIDVALIDITY 2] UIDs valid.', '[UIDNEXT 102] …
```

Cache regex in _process_select_response

---

imapclient/imapclient.py
tests/test_imapclient.py

We've been seeing errors from the `select()` system call because we use more than 1,024 file descriptors in our processes. This patches the `ImapClient` to use the `poll()` system call when available.

poll() when available to surpass 1024 file descriptor limit with select()

---

tests/test_imapclient.py

The LoggerAdapter behavior change has been backported into Python 3.6.4.
Update the check to expect logger.log() call in 3.6.4+ rather than 3.7+.
Fixes #383.

test_imapclient: Fix LoggerAdapter version check

---

imapclient/config.py
livetest-sample.ini

Previously it was failing with the following exception when a default attribute
was set to None.
```console
$ python3 livetest.py livetest-sample.ini
livetest.py:11: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
Traceback (most recent call last):
File "livetest.py", line 1096, in <module>
main()
File "livetest.py", line 1069, in main
host_config = parse_argv()
File "livetest.py", line 1055, in parse_argv
host_config = parse_config_file(ini_path)
File "/home/user/dev/imapclient/imapclient/config.py", line 47, in parse_config_file
parser = SafeConfigParser(get_string_config_defaults())
File "/usr/lib/python3.7/configparser.py", line 1225, in __init__
super().__init__(*args, **kwargs)
File …
```

Fix config file parsing for None attributes

---

imapclient/response_lexer.py

Remove a useless ref cycle in LiteralHandlingIter. This helps the ref count based garbage collection in CPython.

Fix useless ref cycle in lexer

---

imapclient/response_lexer.py
imapclient/response_parser.py
tests/test_imapclient.py

`six.next` is only needed on Python 2.5, which imapclient doesn't claim support for, so there is no need to use it.

Use next instead of six.next

---

imapclient/imapclient.py
tests/test_imapclient.py

With normal APPEND I can upload about 10 msgs/second. With MULTIAPPEND and LITERAL+ I can get about 600 msgs/second. This solves #195.
I am not sure about the  commented out lines - they are part of imaplib's `append` method, but my testing seemed to work without them.
I added the `_literal` object because it seemed that messages should always be sent as literals, even if they are not 8bit.
BTW, great library. One thing I didn't understand once I got hacking on it is the dependency on imaplib. It doesn't seem to add much but makes half the code use a different execution path.
Closes #195 .

MULTIAPPEND and LITERAL+ support

---

imapclient/response_parser.py
tests/test_response_parser.py

This is a minimal attempt to fix bug #390. This fix assumes that when an imap server starts a number with a leading zero, this token should be treated as a string.
As for the suggestion to have a list of attributes that should always be strings:  in our case, we are getting back folder names because we query dovecot for the 'X-MAILBOX' attribute, which is non-standard. I'm not sure if imapclient should maintain/contain a list of (non-standard) attributes that should always be considered a string.
The NIL case might still breaks things, but some manual testing indicates dovecot is smart enough to quote it in that case. I'm not sure if the folder list not being quoted is a dovecot bug or not, but this fix seems easy and makes sense to me.

Prevent converting numbers with leading zeroes to int. (#390)

---

imapclient/imapclient.py

"Logged in/out" traces on info level can easily result in log pollution,
especially where the library is used within other applications that poll
IMAP servers at regular intervals. In such cases the logs will easily
end up containing hundreds/thousands of lines such as:
```
2020-08-31 15:20:09,715| INFO|imapclient.imapclient|Logged in as me@myemail.com
2020-08-31 15:20:09,910| INFO|imapclient.imapclient|Logged out, connection closed
...
```
Also, this makes the behaviour more consistent with other traces - if all
the "normal flow" connection messages are logged on debug level then so
login/logout traces should be.

Moved "Logged in/out" traces from INFO to DEBUG level.

---

imapclient/imapclient.py

This allows mechanisms such as EXTERNAL, GSSAPI, or SCRAM-SHA-256 to be used in the same way as with imaplib.
Tested against Dovecot using SASL GSSAPI (which is a 3-step mechanism).

Allow any custom SASL mechanism to be provided

---

imapclient/tls.py

This fixes:
```python
...
File "/lib/python3.9/site-packages/imapclient/tls.py", line 44, in __init__
imaplib.IMAP4.__init__(self, host, port)
File "/usr/local/lib/python3.9/imaplib.py", line 202, in __init__
self.open(host, port, timeout)
TypeError: open() takes 3 positional arguments but 4 were given
```
https://github.com/python/cpython/blob/v3.9.0/Lib/imaplib.py#L202

add optional timeout parameter to IMAP4_TLS.open

---

imapclient/tls.py

Trying to use [imapautofiler](https://github.com/imapautofiler/imapautofiler) with python 3.9, I get this error:
```
Traceback (most recent call last):
File "/home/chris/lib/virtualenvs/imapautofiler/bin/imapautofiler", line 10, in <module>
sys.exit(main())
File "/home/chris/work/imapautofiler/imapautofiler/imapautofiler/app.py", line 157, in main
conn = client.open_connection(cfg)
File "/home/chris/work/imapautofiler/imapautofiler/imapautofiler/client.py", line 34, in open_connection
return IMAPClient(cfg)
File "/home/chris/work/imapautofiler/imapautofiler/imapautofiler/client.py", line 131, in __init__
self._conn = imapclient.IMAPClient(
File "/home/chris/lib/virtualenvs/imapautofiler/lib/python3.9/site-packages/imapclient/imapclient.py", line 161, in __init__
self._imap = …
```

Fix IMAP4_TLS for imaplib in Python 3.9+

---

imapclient/tls.py

in case the ssl_context argument is None the create_default_context method should be created with CLIENT_AUTH 'Purpose' argument because the default is SERVER_AUTH
```
if ssl_context is None:
ssl_context = ssl.create_default_context(purpose=ssl.Purpose.CLIENT_AUTH)
```

ssl context created with purpose ssl.Purpose.CLIENT_AUTH

---

imapclient/imapclient.py

They were causing warnings from building documentation:
```
/home/boni/base/src/imapclient/imapclient/imapclient.py:docstring of imapclient.imapclient.IMAPClient.sasl_login:40: WARNING: Unexpected indentation.
/home/boni/base/src/imapclient/imapclient/imapclient.py:docstring of imapclient.imapclient.IMAPClient.sasl_login:41: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/boni/base/src/imapclient/imapclient/imapclient.py:docstring of imapclient.imapclient.IMAPClient.sasl_login:43: WARNING: Definition list ends without a blank line; unexpected unindent.
```
The bug is currently visible in hosted documentation: <https://imapclient.readthedocs.io/en/2.2.0/api.html#imapclient.IMAPClient.sasl_login>

Fix missing code block directives in documentation

---

tox.ini

It made me flinch a little every time I saw the end of `tox` output!
```
py27: commands succeeded
ERROR:  py34: InterpreterNotFound: python3.4
py35: commands succeeded
py36: commands succeeded
py37: commands succeeded
py38: commands succeeded
p39: commands succeeded
```

Fix typo in tox envlist

---

tests/test_imapclient.py

There were tests with the identical names, but with `POLL_SUPPORT` patched to `False`.
Changing the test names increased the number of discovered tests by three.

Fix undiscoverable tests due to name shadowing

---

.github/workflows/main.yml
doc/src/contributing.rst
tox.ini

Running `setup.py test` is being deprecated. Its warning can be see in [build log](https://github.com/mjs/imapclient/runs/4337372364?check_suite_focus=true#step:6:7):
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
For this project, its purpose is likely to run unittest with automatic test discovery. So I think it can be replaced with `python -m unittest --verbose`.
Using unittest directly is the easiest replacement I can see. Possible alternatives I have considered:
- The warning suggests using tox. I am unsure how to use tox in GitHub Actions properly. GitHub Actions already sets up an isolated environment for building and testing. Running tox …

Run tests with unittest instead of setup.py

---

doc/src/releases.rst

Building documentation was emitting warnings from the release notes page.
```
/home/boni/base/src/imapclient/doc/src/releases.rst:13: WARNING: Unexpected indentation.
/home/boni/base/src/imapclient/doc/src/releases.rst:14: WARNING: Block quote ends without a blank line; unexpected unindent.
```
It seems that sublists must be wrapped by newlines in reStructuredText. Without the newlines, they are treated as text of the preceding bullet point. This can be seen in the hosted documentation: <https://imapclient.readthedocs.io/en/2.2.0/releases.html#changed>. 
The other commit removes leading indentation from two bullet lists. It seems indented lines on their own are automatically blockquotes in reStructuredText.
I took the opportunity to change the lists to use `-` instead of `*`, to fit the …

Fix render artefacts in changelog

---

examples/idle_selector_example.py
imapclient/imapclient.py
tests/test_imapclient.py

Other than the usual code review, there are things I would like to highlight for checking or consideration.
- I ran unit tests for all supported versions, except for Python 3.4. I would need to set up Docker for it due to SSL library conflicts. If someone already has it set up and can check 3.4 for me, that would be great.
- The included example is significantly longer than existing ones, partially due to its threaded nature. I hope that is not a problem.
- The IDLE example currently in the documentation can potentially be replaced, to use polling instead of a busy loop. I had decided against it because of its simplicity and is a much clearer demonstration of the IDLE API.
closes #450

Allow the connected socket to be polled for data

---

doc/src/contributing.rst
setup.py
tox-all
tox.ini

- Added tox-all script which runs all unit tests against all supported
Python versions using Docker
- Adjusted tox.ini so that old pip and setuptools versions are used
where required for old Python versions
- Updated docs to mention tox-all

Simplify running tests against all Python versions

---

imapclient/imapclient.py
tests/test_imapclient.py

While in #195 it was suggested to implement a `multiappend` function in a way supporting flags and internal date, this was not implemented in #399.
This PR adds the suggested functionality (iterator over `{'msg': ...[, 'flags': ...][, 'date': ...]}`-dicts) in a backwards-compatible manner.

added flags and internaldate capabilites for MULTIAPPEND

---

.github/workflows/lint.yml
doc/src/conf.py
examples/idle_selector_example.py
imapclient/config.py
imapclient/exceptions.py
imapclient/imapclient.py
livetest.py
requirements-dev.txt
setup.py
tests/test_imapclient.py
tests/test_response_lexer.py
tests/test_response_parser.py
tox.ini

Commit f0723402d00c5612a428d3815e4f1e653eb68ff0 ran `black` on the
code base. But since it wasn't being enforced in the CI, it has
drifted away from `black` standarized formatting.
Did the following:
* Added a Github CI job to run `black`
* Added a `black` tox environment
* Ran `black` on the code
* Added the `requirements-dev.txt` file
This has been setup so that it should be easy to add other
checkers/linters in the future as desired.

chore: setup `black` for CI

---

.github/workflows/main.yml
README.rst
setup.py
tox.ini

* Update the code and docs to remove support for Python 3.4 and 3.5.
* State that Python 3.10 is supported.
* Add Python 3.10 to the testing in the CI
Closes: #479

chore: remove support for Python 3.4 & 3.5. Support Python 3.10

---

imapclient/config.py
livetest.py

Commit 92255e96cd555cbf105e6a007c473aeb1ad2d343 introduced a bug by
adding `section` to the argument list, but the callers don't send
`section`.
Fix this by removing `section` from the argument list.
Commit https://github.com/mjs/imapclient/commit/6e6ec34b0e71975134d9492add22361ce4beb2a0 removed the
`tests/utils.py` file but missed updating `livetest.py`
Import `unittest` directly from `livetest.py`
Discovered while working on adding `mypy` testing.

fix: broken `get()` & `getboolean()`

---

imapclient/interact.py

The `optparse` library has been deprecated since Python 3.2 [1]
Convert `optparse` usage to the `argparse` library.
[1] https://docs.python.org/3/library/optparse.html

chore: convert from `optparse` to `argparse`

---

NEWS.rst

Update documentation links

---

livetest.py

It will be gone in the next version of Python.
Fixes #504

Remove usage of deprecated imp module

---

.github/workflows/main.yml
README.rst
setup.py
tox.ini

* Update the code and docs to remove support for Python 3.6.
* State that Python 3.11 is supported.
* Add Python 3.11 to the testing in the CI
Closes: #512

chore: remove support for Python 3.6. Support Python 3.11

---

imapclient/imapclient.py

The function `expunge` can raise an error at the server side, when the function is utilized with *messages*, and the server does not support the capability UIDPLUS.
Closes #496

New function `uid_expunge`, which requires the capability UIDPLUS.

---

tox.ini

In previous versions of `tox` it made sense to use `envdir` to have multiple test environments share the same directory when they had the same requirements.
But since `tox>=4` it no longer makes sense to do this as now `tox` will detect a difference and keep recreating the environment and cause it to be slower than having separate environments. What is happening now is if you run `tox -e black,flake8` it will create the environments. Then run `tox -e black,flake8` again it will again recreate the environments. By removing `envdir` it won't recreate the environments on the second and subsequent runs.

chore: remove `envdir` settings from `tox.ini`

---

imapclient/version.py
pyproject.toml
requirements-dev.txt
tox.ini

This is adding the initial framework for adding type-hints. It adds the running of `mypy` and type-checks nothing in the first commit.
Then adds type-checking of the file `imapclient/version.py` and others can use that as an example of how to add type-hints by updating `pyproject.toml`

Initial framework for adding type-hints and added type-hints to `version.py`

---

.github/dependabot.yml

Add a basic `dependabot.yml` so that PRs will be automatically generated to update the versions of the dependencies.
More information here:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
Once this is merged then Dependabot will propose PRs to update
dependencies.

chore: add `dependabot.yml` to enable automatic PRs

---

.github/workflows/lint.yml
pyproject.toml
requirements-dev.txt
tox.ini

Add an initial `pylint` check. All failing checks were disabled in `pyproject.toml` and no code changes were made.
Recommend in the future to iteratively go through and enable check(s) and resolve issues found.
Closes: #232

chore: add initial `pylint` check

---

imapclient/response_lexer.py
imapclient/tls.py
livetest.py
tests/test_imap_utf7.py

In order to upgrade to `black==23.7.0` some re-formatting is required.
Reformat the code, so that the Dependabot PR will pass CI.

chore: resolve formatting issues so `black==23.7.0` check passes

---

imapclient/datetime_util.py
imapclient/imap_utf7.py
imapclient/tls.py
imapclient/util.py
pyproject.toml

Add type-hints to the files:
* imapclient/util.py
* imapclient/tls.py
* imapclient/imap_utf7.py
* imapclient/datetime_util.py

Add type-hints to more files

---

imapclient/imapclient.py

In current Pythons we can use `dict.pop(key, default)`
Also converted some `**kwargs` to two named arguments with defaults.

chore: remove `pop_with_default()` function

---

imapclient/response_parser.py
imapclient/response_types.py
imapclient/typing_imapclient.py
pyproject.toml

Added type-hints to:
* `response_lexer.py`
* `response_parser.py`
* `response_types.py`

chore: add type-hints to `response_*.py`

---

imapclient/imapclient.py

To comply with RFC 6154. Only the extended LIST command need SPECIAL-USE, not the non-extended LIST command (section 2.0, first paragraph).

Removed SPECIAL-USE capability check

---

imapclient/util.py

Rename the type-var in `utils.py` from `_Atom` to `_TupleAtom` so it isn't confused with the `_Atom` in `typing_imapclient.py`

chore: rename type-var to lessen possible confusion

---

imapclient/imapclient.py
imapclient/response_parser.py
imapclient/response_types.py
tests/test_response_parser.py

A `dataclass` is nicer than a `namedtuple`. Makes it is easy to add type-hints and also they have the added flexibility to customize things if desired.

chore: convert `namedtuple` to `dataclass`

---

imapclient/tls.py

Remove SSL compatibility code for Python 2

---

doc/src/index.rst
doc/src/releases.rst
requirements-dev.txt

...and depend on older sphinx which still supports setup.py build_sphinx for now.

Fix sphinx warnings

---

doc/src/advanced.rst

Spotted by Debian's lint tool `lintian`.

Fix typo in man page: certifcate -> certificate

---

doc/src/conf.py

The Debian lint tool `lintian` noticed that `imapclient` puts its man page to section 1 although this section is intended for
> Executable programs or shell commands
to quote `man man`.
This patch moves the man page to section 7 which seems more suitable.

Move man page to section 7

---

imapclient/imapclient.py
imapclient/response_types.py
requirements-dev.txt

This fixes `mypy` error about `import-not-found`
Closes: #589

chore: add `setuptools` to `requirements-dev.txt`
