mjs/imapclient

- imapclient/imapclient.py
> Get a binary file from the imap socket when doing TLS

- imapclient/response_types.py
- imapclient/test/test_response_parser.py
See the issue #242, not much to add :-)
> Fix #242: handle address without mailbox name or host in Address namedtuple

- imapclient/tls.py
> provide default ssl_context, if not given explicitly [rebased]

- imapclient/imapclient.py
- imapclient/test/test_imapclient.py
- imapclient/test/test_search.py
> Make SEARCH exception message more meaningful to help the user

- imapclient/imapclient.py
- imapclient/livetest.py
- imapclient/test/test_enable.py
... and use it in the integration tests. 
Fixes #136.
> Add ENABLE support

- doc/src/api.rst
- imapclient/exceptions.py
- imapclient/imapclient.py
- livetest.py
- tests/test_enable.py
- tests/test_imapclient.py
- tests/test_search.py
- tests/test_starttls.py
- tests/test_util_functions.py
> Harmonize exceptions names with Error suffix

- doc/src/api.rst
- imapclient/testable_imapclient.py
- tests/imapclient_test.py
- tests/test_imapclient.py
> Move back testable_imapclient to main package

- doc/src/concepts.rst
> Document how to use certificates from certifi

- livetest.py
Some servers show big delays in delivering IDLE notifications.
Fixes #261
> Accommodate IDLE livetest for slow servers

- .travis.yml
> Run tests on pypy

- imapclient/imapclient.py
- tests/test_imapclient.py
> Support quota extension (RFC 2087)

- .travis.yml
- README.rst
- doc/src/index.rst
- setup.py
- start testing against Python 3.7
- mention 3.7 in the docs
> Python 3.7 support

- imapclient/imapclient.py
Might as well fix some typos when I read the code
> Fix minor typo

- imapclient/imapclient.py
This is the standard (RFC 7628) mechanism that's supposed to replace various custom mechanisms like Google's XOAUTH2.
Tested against Gmail.
> Add SASL OAUTHBEARER support

- imapclient/imapclient.py
> Added the Deleted special folder used by Outlook.

- README.rst
- examples/example.py
Added a comment in the examples while going through them. And removed a stray ` in the Readme
> fixed minor typo and added a doc in example

- .github/workflows/lint.yml
- imapclient/__init__.py
- imapclient/config.py
- imapclient/imapclient.py
- requirements-dev.txt
- setup.py
- tests/test_auth.py
- tests/test_enable.py
- tests/test_util_functions.py
- tox.ini
* Setup `flake8` as a tox environment
* Fix issues flagged by `flake8`
* Add running of `flake8` in the CI
> chore: setup `flake8`, fix issues, & add to CI

- imapclient/tls.py
> Default contexts should use SERVER_AUTH not CLIENT_AUTH

- .gitignore
- imapclient/response_types.py
- imapclient/testable_imapclient.py
Some minor fixes. See each commit for description.
> Add some minor fixes

- imapclient/config.py
> Remove configparser deprecation warnings

- .github/workflows/main.yml
Previous versions were deprecated
> Update actions to current versions

- .github/release.yml
As per https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
> Config for Github generated release notes
